### ISSUE TITLE
URL vs Path in page object

### ISSUE THREAD

**Issue by jaysonvaughn** [j0ack/flask-inertia#1]
In views.py page.url is created with request.url, rather than request.path.  It seems that request.path aligns with the other inertia server side adapter.  Does this make sense, or is there a reason to use url that I am not seeing.

**Comment by j0ack** [comment]
Hello, thank you for your report.

I did not based this adapter on existing ones but rather developed it using the `Inertia.js` documentation. 
I don't think there are any upsides or downsides using `request.url` rather than `request.path` based on inertia route implementation.

I'll see how the other `Python` based adapters are implemented and create an `improvement` issue about it.

**Comment by jaysonvaughn** [comment]
No worries.  I only noticed it because i use page.url to set css active states on nav links.

Thanks!
